# Generated by Django 4.2.2 on 2023-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='block_indexing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Leave empty if the current url is canonical curl', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Use maximum 120 characters', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
