# Generated by Django 4.2.2 on 2023-06-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_post_block_indexing_post_canonical_url_post_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
