# Generated by Django 4.2.2 on 2023-06-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_upload_content_type_upload_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='content_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
