# Generated by Django 4.2.2 on 2023-06-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_upload_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='alternative_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
