# Generated by Django 4.2.2 on 2023-06-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_upload_alternative_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='alternative_text',
        ),
    ]
